name: PlugCore
version: '1.1.6'
main: io.plugcore.plugCore.PlugCore
api-version: '1.21'
load: STARTUP
authors: [ Trenton ]
description: PlugCore
website: plugcore.io

commands:
  plugcore:
    description: Main PlugCore command
    usage: /plugcore <link|unlink|status|validate|plugins|reload>
    aliases: [ pc ]

